### ISSUE TITLE
Charts that use a discord server ending in .net aren't accepted

### ISSUE THREAD

**Issue by AnActualEmerald** [Amb1tion/Patrician-Bot#2]
This worked:
![image](https://user-images.githubusercontent.com/4367791/65345469-59daa200-dba8-11e9-9a32-3b780f8e2179.png)

but this didn't:
![image](https://user-images.githubusercontent.com/4367791/65345600-a32af180-dba8-11e9-8699-6a70965d65cc.png)

I checked your code and the regex your using to search the image url only checks for .com

**Comment by Amb1tion** [comment]
Fixed in the rewrite branch.
