### ISSUE TITLE
disable command does not work

### ISSUE THREAD

**Issue by smokepcpeveryday** [Amb1tion/Patrician-Bot#4]
when I do !disable chart it just outputs 

You can disable the following:
'quote', 'lyrics', 'countdown', 'joindate', 'yt', 'disable', 'unload', 'choose', 'lp', 'add', 'monthly', 'clear', 'enable', 'alltimey', 'alltime', 'ball', 'reload', 'chart', 'weekly', 'fm', 'regex', 'rym', 'submit', 'brave', 'taste', 'load', 'yearly'

**Comment by Amb1tion** [comment]
This might be a case of you not having the "manage server" permission , you need that to enable/disable any bot commands.
