### ISSUE TITLE
Bot seems to die when I add it to a specific server

### ISSUE THREAD

**Issue by s0hv** [Amb1tion/Patrician-Bot#5]
I added the bot to my server which is quite big and it just stopped working after that everywhere (everywhere being at least a few server) it seems. My server's id is 217677285442977792

**Comment by s0hv** [comment]
Also I forgot to say it but the bot doesn't work in that server at all

**Comment by Amb1tion** [comment]
This was my VPS running out of memory and a lack of sharding in main.py while initializing the client , should be fine now.
