### ISSUE TITLE
some users get a blank chart

### ISSUE THREAD

**Issue by ftrbnd** [Amb1tion/Patrician-Bot#7]
<img width="599" alt="Screen Shot 2020-05-27 at 11 28 18 PM" src="https://user-images.githubusercontent.com/46335023/83106706-c714d000-a071-11ea-9634-d4be74bb86a6.png">

this user has already submitted their username, and isn't the only one getting an empty chart

**Comment by Amb1tion** [comment]
The next time this happens could you pose their username so i can troubleshoot this better ?
